import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Datas relativas a 2026-05-21
const hoje = new Date("2026-05-21");
const d = (offset: number): Date => {
  const dt = new Date(hoje);
  dt.setDate(dt.getDate() + offset);
  return dt;
};

// Buscar etiquetas existentes para reutilizar
async function main() {
  const etiquetas = await prisma.etiqueta.findMany();
  const etNome = (nome: string) => etiquetas.find(e => e.nome === nome)?.id;

  // ── 50 clientes diversificados ────────────────────────────────────────────
  const clientesData = [
    // ── VIP EMBAIXADORA (4) ─────────────────────────────────────────────────
    {
      nome: "Helena Vasconcelos", telefone: "912001001", email: "helena.vasconcelos@gmail.com",
      estado: "vip_embaixadora", totalSessoes: 32, totalGasto: 1520, ultimaSessao: d(-5),
      dataNascimento: new Date("1975-03-12"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Sândalo, rosa e incenso — aromas profundos e aterradores. Diz que a transportam para outro estado de consciência.",
      historicoCondicoesAlergias: "Artrose no joelho direito. Evitar pressão directa na articulação. Sem alergias.",
      historicoEstadoEmocional: "Muito equilibrada e centrada. Pratica meditação diariamente. Usa as sessões como aprofundamento da prática.",
      historicoZonasTensao: "Joelho direito (artrose), ombros por tensão postural de pianista.",
      historicoUltimaPausa: "Sem pausas em 2 anos. Frequência quinzenal constante.",
      notasPessoais: "Pianista profissional. Leva sempre flores para a Essence. Recomendou 6 clientes. Aniversário em março.",
      etiquetas: [etNome("VIP")].filter(Boolean) as string[],
    },
    {
      nome: "Francisca Cunha Barros", telefone: "916002002", email: "francisca.cb@sapo.pt",
      estado: "vip_embaixadora", totalSessoes: 28, totalGasto: 1400, ultimaSessao: d(-3),
      dataNascimento: new Date("1968-09-05"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Neroli e pétalas de rosa. Sensível a aromas amadeirados intensos — evitar.",
      historicoCondicoesAlergias: "Menopausa — afrontamentos frequentes. Aromas refrescantes prioritários. Pressão suave.",
      historicoEstadoEmocional: "Vai e vem emocionalmente consoante os afrontamentos. Sessões têm efeito regulador notável.",
      historicoZonasTensao: "Zona cervical e cabeça (tensão menopausal). Pernas pesadas.",
      historicoUltimaPausa: "Pausa de 4 semanas em agosto por férias. Voltou com ansiedade acumulada.",
      notasPessoais: "Diretora de escola. Traz sempre uma aluna nova. Gosta de silêncio absoluto.",
      etiquetas: [etNome("VIP")].filter(Boolean) as string[],
    },
    {
      nome: "Cristina Matos Pereira", telefone: "963003003", email: "cristina.mp@hotmail.com",
      estado: "vip_embaixadora", totalSessoes: 24, totalGasto: 1200, ultimaSessao: d(-8),
      dataNascimento: new Date("1971-11-28"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Bergamota e menta — estimulantes e revigorantes. Prefere manhãs.",
      historicoCondicoesAlergias: "Fibromialgia diagnosticada. Pressão muito suave generalizada. Sensível a temperatura.",
      historicoEstadoEmocional: "Dias bons e maus conforme a fibromialgia. Sessões são o seu 'reset' emocional.",
      historicoZonasTensao: "Generalizado (fibromialgia). Costas superiores e coxas mais afetadas.",
      historicoUltimaPausa: "Nunca parou mais de 3 semanas — sente agravamento da fibromialgia.",
      notasPessoais: "Contabilista. Muito informada sobre a sua condição. Traz sempre relatórios médicos.",
      etiquetas: [etNome("VIP")].filter(Boolean) as string[],
    },
    {
      nome: "Marta Rebelo Figueiredo", telefone: "937004004", email: "marta.rf@gmail.com",
      estado: "vip_embaixadora", totalSessoes: 20, totalGasto: 980, ultimaSessao: d(-12),
      dataNascimento: new Date("1983-05-20"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "email", temWhatsapp: false, aceitaMarketing: true,
      historicoAromasPreferidos: "Eucalipto e tea tree — limpeza e clareza. Ambiente clínico e profissional.",
      historicoCondicoesAlergias: "Alergia ao látex (usar luvas alternativas). Rinite alérgica — evitar aromas florais fortes.",
      historicoEstadoEmocional: "Muito racional, pouco expressiva. Desfruta quando consegue 'desligar'.",
      historicoZonasTensao: "Pescoço (alergia provoca tensão). Ombros por trabalho de laboratório.",
      historicoUltimaPausa: "Pausa de 6 semanas para congresso internacional. Voltou 'entupida' de tensão.",
      notasPessoais: "Investigadora científica. Prefere comunicação por email. Alérgica ao látex — IMPORTANTE.",
      etiquetas: [etNome("VIP")].filter(Boolean) as string[],
    },

    // ── ATIVA FREQUENTE (8) ──────────────────────────────────────────────────
    {
      nome: "Patrícia Nunes", telefone: "912005005", email: "patricia.nunes@gmail.com",
      estado: "ativa_frequente", totalSessoes: 15, totalGasto: 700, ultimaSessao: d(-18),
      dataNascimento: new Date("1986-07-14"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Lavanda e camomila — relaxamento profundo ao final do dia.",
      historicoCondicoesAlergias: "Enxaqueca crónica. Protocolo de massagem craniana. Aromas suaves apenas.",
      historicoEstadoEmocional: "Muito stressada com trabalho. Usa as sessões como 'valvula de escape'.",
      historicoZonasTensao: "Cabeça e nuca (enxaqueca). Ombros e trapézio.",
      historicoUltimaPausa: "Pausa de 3 semanas em dezembro. Enxaqueca agravou.",
      notasPessoais: "Gestora de marketing. Agenda sempre ao final do dia, 18h30. Pontualíssima.",
      etiquetas: [] as string[],
    },
    {
      nome: "Joana Esteves Leal", telefone: "926006006", email: "joana.el@outlook.pt",
      estado: "ativa_frequente", totalSessoes: 13, totalGasto: 620, ultimaSessao: d(-20),
      dataNascimento: new Date("1990-02-08"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Ylang-ylang e jasmim — femininos e quentes.",
      historicoCondicoesAlergias: "Escoliose leve. Trabalhar sempre com almofada de apoio lombar.",
      historicoEstadoEmocional: "Muito ansiosa antes de cada sessão, completamente tranquila no fim.",
      historicoZonasTensao: "Lombar (escoliose). Costas superiores.",
      historicoUltimaPausa: "Frequência mensal constante há 13 meses.",
      notasPessoais: "Enfermeira. Turno rotativo — horários variados. Avisar com antecedência de mudanças.",
      etiquetas: [] as string[],
    },
    {
      nome: "Rute Carvalho Santos", telefone: "917007007", email: "rute.cs@gmail.com",
      estado: "ativa_frequente", totalSessoes: 11, totalGasto: 530, ultimaSessao: d(-15),
      dataNascimento: new Date("1988-12-03"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Hortelã e eucalipto — manhãs energéticas. Não gosta de florais.",
      historicoCondicoesAlergias: "Síndrome do intestino irritável — evitar pressão abdominal profunda.",
      historicoEstadoEmocional: "Muito positiva. Usa as sessões como celebração do bem-estar.",
      historicoZonasTensao: "Zona abdominal (SII). Costas inferiores.",
      historicoUltimaPausa: "Sem pausas há 11 meses.",
      notasPessoais: "Personal trainer. Muito consciente do corpo. Sugere técnicas novas às vezes.",
      etiquetas: [] as string[],
    },
    {
      nome: "Filipa Andrade", telefone: "965008008", email: "filipa.andrade@live.pt",
      estado: "ativa_frequente", totalSessoes: 10, totalGasto: 480, ultimaSessao: d(-22),
      dataNascimento: new Date("1993-08-19"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Rosa e sândalo — luxuosos e envolventes.",
      historicoCondicoesAlergias: "Sem condições. Tensão muscular crónica por postura.",
      historicoEstadoEmocional: "Equilibrada. Sessões são rotina de manutenção.",
      historicoZonasTensao: "Pescoço e ombros. Punhos (trabalho ao computador).",
      historicoUltimaPausa: "Pausa de 5 semanas por viagem ao Brasil.",
      notasPessoais: "Designer gráfica. Trabalha de casa. Prefere manhãs de 2ª e 4ª feira.",
      etiquetas: [] as string[],
    },
    {
      nome: "Andreia Fonseca Melo", telefone: "912009009", email: "andreia.fm@gmail.com",
      estado: "ativa_frequente", totalSessoes: 9, totalGasto: 420, ultimaSessao: d(-25),
      dataNascimento: new Date("1980-04-30"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Rosmaninho e menta — portugueses e familiares.",
      historicoCondicoesAlergias: "Hérnia cervical C5-C6. Muito cuidado na zona cervical.",
      historicoEstadoEmocional: "Ansiosa por natureza. Sessões ajudam muito com a ansiedade.",
      historicoZonasTensao: "Cervical (hérnia). Cabeça e nuca.",
      historicoUltimaPausa: "Pausa de 2 meses após cirurgia menor. Voltou com cervical bloqueada.",
      notasPessoais: "Farmacêutica. Muito informada sobre suplementação. Prefere ser contactada por email.",
      etiquetas: [] as string[],
    },
    {
      nome: "Susana Teixeira Bento", telefone: "935010010", email: "susana.tb@sapo.pt",
      estado: "ativa_frequente", totalSessoes: 8, totalGasto: 380, ultimaSessao: d(-28),
      dataNascimento: new Date("1977-01-16"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Camomila e lavanda — calmantes e suaves.",
      historicoCondicoesAlergias: "Hipotiroidismo. Metabolismo lento, faz frio facilmente.",
      historicoEstadoEmocional: "Oscilações de humor pelo hipotiroidismo. Sessões estabilizam o estado emocional.",
      historicoZonasTensao: "Pernas pesadas (hipotiroidismo). Cervical e ombros.",
      historicoUltimaPausa: "Frequência mensal estável.",
      notasPessoais: "Professora do 1º ciclo. Turno manhã, livre às 14h. Marido também quer vir um dia.",
      etiquetas: [] as string[],
    },
    {
      nome: "Verónica Saraiva", telefone: "916011011", email: "veronica.s@gmail.com",
      estado: "ativa_frequente", totalSessoes: 7, totalGasto: 350, ultimaSessao: d(-30),
      dataNascimento: new Date("1995-06-22"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Verbena e bergamota — frescos e jovens.",
      historicoCondicoesAlergias: "Sem condições. Corrida de rua — tensão muscular desportiva.",
      historicoEstadoEmocional: "Muito energética e positiva. Sessões pré/pós corrida.",
      historicoZonasTensao: "Pernas (corredora). Glúteos e banda iliotibial.",
      historicoUltimaPausa: "Sem pausas desde outubro.",
      notasPessoais: "Corredora de meia maratona. Sessões alinhadas com calendário de provas.",
      etiquetas: [] as string[],
    },
    {
      nome: "Núria Campos", telefone: "962012012", email: "nuria.campos@gmail.com",
      estado: "ativa_frequente", totalSessoes: 6, totalGasto: 290, ultimaSessao: d(-16),
      dataNascimento: new Date("1987-10-11"), comoNosConheceu: "google", fonte: "calendly",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Gerânio e palmarosa — femininos e equilibrantes.",
      historicoCondicoesAlergias: "TPM intensa — sessões pré-menstrual são as mais eficazes.",
      historicoEstadoEmocional: "Varia muito com o ciclo. Documenta bem quando vem.",
      historicoZonasTensao: "Lombar e abdómen (TPM). Cabeça.",
      historicoUltimaPausa: "Sem pausas, mas frequência irregular (ciclo).",
      notasPessoais: "Nutricionista. Muito interessada em holístico. Quer eventualmente fazer curso de aromaterapia.",
      etiquetas: [] as string[],
    },

    // ── ATIVA RECENTE (8) ────────────────────────────────────────────────────
    {
      nome: "Carla Moreira Dias", telefone: "912013013", email: "carla.md@gmail.com",
      estado: "ativa_recente", totalSessoes: 4, totalGasto: 190, ultimaSessao: d(-10),
      dataNascimento: new Date("1991-09-02"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Lavanda e baunilha — quentes e acolhedores.",
      historicoCondicoesAlergias: "Sem condições. Ansiedade generalizada.",
      historicoEstadoEmocional: "Trabalho com ansiedade diagnosticada. Sessões são terapêuticas.",
      historicoZonasTensao: "Ombros e pescoço. Mandíbula (aperta os dentes).",
      historicoUltimaPausa: "Começou há 4 meses. Sem pausas.",
      notasPessoais: "Arquiteta. Muito criativa, stress elevado de prazos. Gosta de ouvir música suave.",
      etiquetas: [] as string[],
    },
    {
      nome: "Rita Guerreiro", telefone: "917014014", email: "rita.guerreiro@hotmail.com",
      estado: "ativa_recente", totalSessoes: 3, totalGasto: 145, ultimaSessao: d(-7),
      dataNascimento: new Date("1994-12-18"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Neroli e camomila — delicados e suaves.",
      historicoCondicoesAlergias: "Gravidez 10 semanas. Protocolo pré-natal mínimo, muito cuidado.",
      historicoEstadoEmocional: "Ansiosa com a gravidez, primeiro trimestre. Sessões ajudam muito.",
      historicoZonasTensao: "Náuseas tensionam o abdómen. Costas superiores.",
      historicoUltimaPausa: "Começou há 3 semanas.",
      notasPessoais: "Professora de yoga, paradoxalmente muito tensa. 10 semanas de gravidez — cautela máxima.",
      etiquetas: [etNome("Gravidez")].filter(Boolean) as string[],
    },
    {
      nome: "Alexandra Moura", telefone: "963015015", email: "alex.moura@gmail.com",
      estado: "ativa_recente", totalSessoes: 3, totalGasto: 140, ultimaSessao: d(-14),
      dataNascimento: new Date("1984-07-07"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Cedro e patchouli — terra e estabilidade.",
      historicoCondicoesAlergias: "Cirurgia ao disco (L5-S1) há 2 anos. Protocolo pós-cirúrgico.",
      historicoEstadoEmocional: "Aliviada desde a cirurgia. Sessões como prevenção de recidiva.",
      historicoZonasTensao: "Lombar cirúrgica (monitorizar). Pernas (irradiação pós-cirurgia).",
      historicoUltimaPausa: "Começou há 2 meses.",
      notasPessoais: "Nutricionista hospitalar. Veio por indicação do fisiatra. Traz relatório cirúrgico.",
      etiquetas: [] as string[],
    },
    {
      nome: "Diana Albuquerque", telefone: "916016016", email: "diana.alb@gmail.com",
      estado: "ativa_recente", totalSessoes: 2, totalGasto: 90, ultimaSessao: d(-20),
      dataNascimento: new Date("1997-03-25"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Manga e maracujá (óleos frutados) — jovem e refrescante.",
      historicoCondicoesAlergias: "Sem condições. Tensão de estudante.",
      historicoEstadoEmocional: "Estudo de medicina — muito stressada com exames. Sessões são pausa.",
      historicoZonasTensao: "Pescoço e ombros (muitas horas a estudar). Olhos cansados.",
      historicoUltimaPausa: "2 sessões apenas.",
      notasPessoais: "Estudante de medicina. Orçamento limitado — sessões como investimento em si.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Isabel Monteiro", telefone: "912017017", email: "isabel.m@live.pt",
      estado: "ativa_recente", totalSessoes: 2, totalGasto: 95, ultimaSessao: d(-25),
      dataNascimento: new Date("1969-08-14"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "telefone", temWhatsapp: false, aceitaMarketing: false,
      historicoAromasPreferidos: "Olíbano e mirra — tradicionais e espirituais.",
      historicoCondicoesAlergias: "Osteoporose. Pressão muito suave nos ossos.",
      historicoEstadoEmocional: "Reservada. Abre-se progressivamente. Viuvez recente.",
      historicoZonasTensao: "Costas (osteoporose). Quadris.",
      historicoUltimaPausa: "2 sessões em fevereiro e março.",
      notasPessoais: "Reformada. Não usa WhatsApp — contactar por telefone. Perdeu o marido em 2025.",
      etiquetas: [] as string[],
    },
    {
      nome: "Mónica Rodrigues Freitas", telefone: "935018018", email: "monica.rf@gmail.com",
      estado: "ativa_recente", totalSessoes: 2, totalGasto: 90, ultimaSessao: d(-18),
      dataNascimento: new Date("1992-11-30"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Pétalas de rosa e geranio — delicados.",
      historicoCondicoesAlergias: "Sem condições. Tensão por aleitamento materno.",
      historicoEstadoEmocional: "Cansada (bebé de 6 meses). Sessões são o seu momento.",
      historicoZonasTensao: "Pescoço e ombros (amamentação). Costas superiores.",
      historicoUltimaPausa: "Começou há 2 meses pós-parto.",
      notasPessoais: "Mãe recente. Bebé de 6 meses. Deixa o bebé com o marido para vir. Precisa de tempo.",
      etiquetas: [] as string[],
    },
    {
      nome: "Beatriz Drummond", telefone: "916019019", email: "bea.drummond@gmail.com",
      estado: "ativa_recente", totalSessoes: 1, totalGasto: 55, ultimaSessao: d(-28),
      dataNascimento: new Date("2000-05-08"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Maçã e baunilha — doces e reconfortantes.",
      historicoCondicoesAlergias: "Sem condições. Ansiedade de desempenho.",
      historicoEstadoEmocional: "Bailarina — pressão intensa de corpo e imagem. Sessão foi revelação.",
      historicoZonasTensao: "Pés e tornozelos. Costas, coxas.",
      historicoUltimaPausa: "1 sessão, última semana de abril.",
      notasPessoais: "Bailarina de 26 anos. Primeira sessão de massagem — adorou. Alto potencial.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },

    // ── NOVO (6) ─────────────────────────────────────────────────────────────
    {
      nome: "Luísa Pimentel", telefone: "912020020", email: "luisa.pimentel@gmail.com",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1988-02-14"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: "Referiu ansiedade crónica.",
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Entrou em contacto pelo Instagram. Perguntou sobre sessão de aromaterapia para ansiedade.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Érica Vasquez", telefone: "917021021", email: "erica.v@gmail.com",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1995-07-19"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Encontrou pelo Google 'massagem bem-estar Lisboa'. Pediu orçamento.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Paula Teixeira", telefone: "963022022", email: "paulatx@sapo.pt",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1973-10-05"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: "Diabetes tipo 2. Verificar circulação.",
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Recomendada pela Cristina Matos. Tem diabetes — ver protocolo adequado antes de marcar.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Sara Menezes Costa", telefone: "916023023", email: "sara.mc@outlook.pt",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1999-01-31"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Viu story dos bastidores. Quer oferecer sessão à mãe como prenda de aniversário.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Mariana Figueiras", telefone: "912024024", email: "mariana.fig@gmail.com",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1996-04-04"), comoNosConheceu: "instagram", fonte: "calendly",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Marcou pelo Calendly mas cancelou à última hora. Reagendar com desconto de fidelização.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },
    {
      nome: "Clara Azevedo", telefone: "935025025", email: "clara.azevedo@gmail.com",
      estado: "novo", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: new Date("1982-08-27"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: "Esclerose múltipla estável. Protocolo específico.",
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Recomendada por médica neurologista. Esclerose múltipla estável — consultar médica antes de iniciar.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },

    // ── LEAD (5) ─────────────────────────────────────────────────────────────
    {
      nome: "Inês Bettencourt", telefone: "912026026", email: "ines.bettencourt@gmail.com",
      estado: "lead", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Comentou 'quero muito ir' no post do Instagram. Ainda não contactou directamente.",
      etiquetas: [] as string[],
    },
    {
      nome: "Neuza Ferreira Lima", telefone: "917027027", email: "neuza.fl@gmail.com",
      estado: "lead", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: false, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Preencheu formulário do Google. Quer saber sobre preços e localização. Não usa WhatsApp.",
      etiquetas: [] as string[],
    },
    {
      nome: "Pilar Santos Vieira", telefone: "963028028", email: "pilar.sv@outlook.pt",
      estado: "lead", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Colega da Patrícia Nunes. Disse que quer marcar 'assim que tiver tempo'. Follow-up em junho.",
      etiquetas: [] as string[],
    },
    {
      nome: "Rafaela Coutinho", telefone: "916029029", email: "rafa.c@gmail.com",
      estado: "lead", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Participou no sorteio de Instagram. Ganhou desconto de 20% na primeira sessão. Validade: 30/06.",
      etiquetas: [] as string[],
    },
    {
      nome: "Débora Almeida Neves", telefone: "912030030", email: "debora.an@sapo.pt",
      estado: "lead", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Pediu informações sobre sessões de grupo ou casal. Pesquisou no Google.",
      etiquetas: [] as string[],
    },

    // ── VIP EM RISCO (6) ─────────────────────────────────────────────────────
    {
      nome: "Graça Pinheiro Costa", telefone: "912031031", email: "graca.pc@hotmail.com",
      estado: "vip_em_risco", totalSessoes: 16, totalGasto: 760, ultimaSessao: d(-38),
      dataNascimento: new Date("1966-10-23"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Lavanda francesa e neroli. Reage muito bem a florais.",
      historicoCondicoesAlergias: "Artrite reumatoide. Flares imprevisíveis — avisar antes de sessão intensa.",
      historicoEstadoEmocional: "Boa disposição quando não está em flare. Frustração quando dói.",
      historicoZonasTensao: "Mãos e punhos (artrite). Joelhos. Generalizado em flare.",
      historicoUltimaPausa: "Parou em março sem aviso. Possível flare. Verificar.",
      notasPessoais: "Cliente fidelizada há 3 anos. Parou de vir sem explicação. Abordagem cuidadosa.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Olga Tavares Mendes", telefone: "917032032", email: "olga.tm@gmail.com",
      estado: "vip_em_risco", totalSessoes: 12, totalGasto: 580, ultimaSessao: d(-42),
      dataNascimento: new Date("1978-05-11"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Bergamota e limão — cítricos refrescantes.",
      historicoCondicoesAlergias: "Psoríase. Pele muito sensível — óleos hipoalergénicos.",
      historicoEstadoEmocional: "Psoríase piora com stress. Ciclo vicioso que as sessões ajudam a quebrar.",
      historicoZonasTensao: "Zona afetada pela psoríase (couro cabeludo, cotovelos). Costas.",
      historicoUltimaPausa: "Sem sessões desde início de abril. Não respondeu a mensagem.",
      notasPessoais: "A psoríase pode estar em surto — abordagem com empatia, não pressão.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Cláudia Henriques", telefone: "962033033", email: "claudia.h@gmail.com",
      estado: "vip_em_risco", totalSessoes: 10, totalGasto: 490, ultimaSessao: d(-35),
      dataNascimento: new Date("1984-12-01"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Incenso e mirra — espirituais e profundos.",
      historicoCondicoesAlergias: "Depressão tratada. Cuidado no tipo de conversa durante sessão.",
      historicoEstadoEmocional: "Luta contra depressão. Sessões fazem parte do tratamento holístico.",
      historicoZonasTensao: "Costas superiores (tensão emocional). Pescoço.",
      historicoUltimaPausa: "Parou em abril. Psicóloga disse que está em fase de reclusão.",
      notasPessoais: "Abordagem muito suave e acolhedora. Não pressionar. Mensagem de carinho apenas.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Marisa Belo Santos", telefone: "916034034", email: "marisa.bs@sapo.pt",
      estado: "vip_em_risco", totalSessoes: 8, totalGasto: 390, ultimaSessao: d(-50),
      dataNascimento: new Date("1979-03-18"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: false, aceitaMarketing: true,
      historicoAromasPreferidos: "Ylang-ylang e sândalo.",
      historicoCondicoesAlergias: "Hipertensão. Evitar pressão forte. Sem cafeína antes da sessão.",
      historicoEstadoEmocional: "Hipertensão controlada por medicação. Sessões ajudam a baixar pressão.",
      historicoZonasTensao: "Pescoço e cabeça. Costas superiores.",
      historicoUltimaPausa: "Última sessão há quase 2 meses. Não usa WhatsApp — contactar por email.",
      notasPessoais: "Muito meticulosa com horários. Prefere email. Hipertensa — avisar antes de técnicas intensas.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Lena Pacheco", telefone: "912035035", email: "lena.pacheco@gmail.com",
      estado: "vip_em_risco", totalSessoes: 7, totalGasto: 345, ultimaSessao: d(-45),
      dataNascimento: new Date("1989-06-07"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Rosa e jasmin — luxuosos.",
      historicoCondicoesAlergias: "Sem condições. Endometriose — dor pélvica crónica.",
      historicoEstadoEmocional: "Endometriose afeta muito o humor. Alívio notável após sessões.",
      historicoZonasTensao: "Zona pélvica (endometriose). Lombar. Abdómen.",
      historicoUltimaPausa: "Parou em março, possivelmente cirurgia de endometriose.",
      notasPessoais: "Possível cirurgia de endometriose. Aguardar notícias antes de contactar.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Natacha Vilhena", telefone: "935036036", email: "natacha.v@outlook.pt",
      estado: "vip_em_risco", totalSessoes: 6, totalGasto: 290, ultimaSessao: d(-40),
      dataNascimento: new Date("1993-09-14"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Menta e eucalipto.",
      historicoCondicoesAlergias: "Sem condições. Burnout profissional.",
      historicoEstadoEmocional: "Burnout severo em março. Sessões eram o único momento de pausa.",
      historicoZonasTensao: "Corpo todo em tensão (burnout). Pescoço e ombros em especial.",
      historicoUltimaPausa: "Parou quando o burnout piorou — irónico. Precisa urgente de voltar.",
      notasPessoais: "Advogada com burnout. Abordagem: 'o teu corpo precisa de ti agora'. Não mencionar trabalho.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },

    // ── REATIVAÇÃO (7) ───────────────────────────────────────────────────────
    {
      nome: "Vanessa Correia", telefone: "912037037", email: "vanessa.c@gmail.com",
      estado: "reativacao", totalSessoes: 5, totalGasto: 230, ultimaSessao: d(-80),
      dataNascimento: new Date("1985-04-12"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Baunilha e canela — quentes e envolventes.",
      historicoCondicoesAlergias: "Sem condições. Recém divorciada — fase difícil.",
      historicoEstadoEmocional: "Divorciou em fevereiro. Sessões eram a sua âncora. Parou de vir.",
      historicoZonasTensao: "Pescoço e ombros (stress emocional). Peito tenso.",
      historicoUltimaPausa: "Parou após o divórcio. 80 dias sem sessão.",
      notasPessoais: "Divórcio recente. Abordagem amorosa e sem julgamento. Não perguntar sobre o ex.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Rosário Baptista", telefone: "916038038", email: "rosario.b@sapo.pt",
      estado: "reativacao", totalSessoes: 4, totalGasto: 195, ultimaSessao: d(-95),
      dataNascimento: new Date("1960-02-22"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "telefone", temWhatsapp: false, aceitaMarketing: false,
      historicoAromasPreferidos: "Lavanda e rosa.",
      historicoCondicoesAlergias: "Diabetes tipo 1. Circulação comprometida nas pernas.",
      historicoEstadoEmocional: "Reservada. Viúva recente. Sessões ajudavam muito.",
      historicoZonasTensao: "Pernas (diabetes). Costas.",
      historicoUltimaPausa: "Parou há 3 meses. Ligou para dizer que estava bem mas sem data para voltar.",
      notasPessoais: "Não usa smartphone. Ligar — não usar WhatsApp. Não quer newsletters.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Joana Vaz Pires", telefone: "962039039", email: "joana.vp@gmail.com",
      estado: "reativacao", totalSessoes: 3, totalGasto: 145, ultimaSessao: d(-70),
      dataNascimento: new Date("1998-11-05"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Maracujá e ylang-ylang.",
      historicoCondicoesAlergias: "Sem condições. Ansiedade social.",
      historicoEstadoEmocional: "Ansiedade social — o espaço calmo da Essence ajuda muito.",
      historicoZonasTensao: "Ombros e peito (ansiedade). Maxilar.",
      historicoUltimaPausa: "Parou após terminar estágio. Problema financeiro temporário.",
      notasPessoais: "Acabou o estágio, ficou sem rendimento. Oferecer plano flexível ou parcelado.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Teresa Magalhães", telefone: "912040040", email: "teresa.mag@hotmail.com",
      estado: "reativacao", totalSessoes: 3, totalGasto: 130, ultimaSessao: d(-65),
      dataNascimento: new Date("1972-07-16"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "email", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Cedro e sândalo.",
      historicoCondicoesAlergias: "Cancro da mama — em remissão há 2 anos.",
      historicoEstadoEmocional: "Guerreira. Sessões fazem parte da recuperação.",
      historicoZonasTensao: "Zona peitoral (cicatriz cirúrgica). Braço direito (linfedema leve).",
      historicoUltimaPausa: "Parou há 2 meses. Consultas de oncologia frequentes.",
      notasPessoais: "Sobrevivente de cancro mama. Protocolo específico — sem pressão na axila direita. Muito corajosa.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Miriam Ferreira", telefone: "917041041", email: "miriam.f@gmail.com",
      estado: "reativacao", totalSessoes: 2, totalGasto: 90, ultimaSessao: d(-85),
      dataNascimento: new Date("1991-03-28"), comoNosConheceu: "instagram", fonte: "calendly",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Lavanda e bergamota.",
      historicoCondicoesAlergias: "Sem condições. Hipermobilidade articular.",
      historicoEstadoEmocional: "Muito flexível mas com dores crónicas (hipermobilidade). Surpresa positiva com massagem.",
      historicoZonasTensao: "Joelhos e tornozelos (hipermobilidade). Coluna instável.",
      historicoUltimaPausa: "Mudou de cidade (Porto). Estava a considerar parar.",
      notasPessoais: "Mudou para Porto. Ver se há alternativa ou se vem quando está em Lisboa.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Sónia Abreu", telefone: "963042042", email: "sonia.abreu@sapo.pt",
      estado: "reativacao", totalSessoes: 2, totalGasto: 80, ultimaSessao: d(-90),
      dataNascimento: new Date("1983-06-04"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Eucalipto.",
      historicoCondicoesAlergias: "Grávida de 5 meses (quando veio). Protocolo pré-natal.",
      historicoEstadoEmocional: "Tinha vindo grávida. Bebé já deve ter nascido.",
      historicoZonasTensao: "Lombar e pernas.",
      historicoUltimaPausa: "Veio 2 vezes grávida. Bebé deve ter nascido em fevereiro.",
      notasPessoais: "Bebé deve ter nascido em fevereiro 2026. Contactar com parabéns e oferta pós-parto.",
      etiquetas: [etNome("Reengagement")].filter(Boolean) as string[],
    },
    {
      nome: "Carmo Leandro", telefone: "916043043", email: "carmo.l@live.pt",
      estado: "reativacao", totalSessoes: 1, totalGasto: 45, ultimaSessao: d(-100),
      dataNascimento: new Date("2001-09-13"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Lavanda — relaxamento.",
      historicoCondicoesAlergias: "Sem condições. Estudante com stress de exames.",
      historicoEstadoEmocional: "Chegou em pânico de exames. Saiu tranquila. Disse que voltava.",
      historicoZonasTensao: "Ombros e pescoço.",
      historicoUltimaPausa: "1 sessão apenas. Época de exames novamente.",
      notasPessoais: "Estudante universitária. Pode estar em época de exames. Mensagem positiva e sem pressão.",
      etiquetas: [etNome("Nova cliente")].filter(Boolean) as string[],
    },

    // ── PERDIDA (4) ──────────────────────────────────────────────────────────
    {
      nome: "Ana Catarina Brás", telefone: "912044044", email: "acbras@gmail.com",
      estado: "perdida", totalSessoes: 8, totalGasto: 380, ultimaSessao: d(-200),
      dataNascimento: new Date("1976-12-08"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: "Sândalo e vetiver.",
      historicoCondicoesAlergias: "Sem condições.",
      historicoEstadoEmocional: "Nunca partilhou muito. Comunicação difícil.",
      historicoZonasTensao: "Costas e ombros.",
      historicoUltimaPausa: "Não responde a mensagens há 6 meses. Desistiu sem aviso.",
      notasPessoais: "Não responde. Remover de campanhas activas mas manter registo.",
      etiquetas: [] as string[],
    },
    {
      nome: "Flávia Duarte", telefone: "935045045", email: "flavia.d@gmail.com",
      estado: "perdida", totalSessoes: 5, totalGasto: 225, ultimaSessao: d(-180),
      dataNascimento: new Date("1989-08-20"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "email", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: "Lavanda.",
      historicoCondicoesAlergias: "Sem condições.",
      historicoEstadoEmocional: "Positiva mas irregular.",
      historicoZonasTensao: "Costas.",
      historicoUltimaPausa: "Mudou para o Algarve. Não responde a emails há 6 meses.",
      notasPessoais: "Mudança para Algarve — caso encerrado.",
      etiquetas: [] as string[],
    },
    {
      nome: "Bruna Esteves", telefone: "962046046", email: "bruna.esteves@gmail.com",
      estado: "perdida", totalSessoes: 3, totalGasto: 130, ultimaSessao: d(-210),
      dataNascimento: new Date("1994-05-30"), comoNosConheceu: "google", fonte: "google",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null,
      historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null,
      historicoZonasTensao: null,
      historicoUltimaPausa: "Não voltou. Tentámos 3 vezes. Sem resposta.",
      notasPessoais: "3 tentativas de contacto sem resposta. Encerrar.",
      etiquetas: [] as string[],
    },
    {
      nome: "Liliana Godinho", telefone: "916047047", email: "lili.g@sapo.pt",
      estado: "perdida", totalSessoes: 2, totalGasto: 80, ultimaSessao: d(-240),
      dataNascimento: new Date("1981-01-17"), comoNosConheceu: "referencia", fonte: "referencia",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null,
      historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null,
      historicoZonasTensao: null,
      historicoUltimaPausa: "Não quis continuar. Disse que 'não era para ela'.",
      notasPessoais: "Não quis continuar após 2 sessões. Caso encerrado.",
      etiquetas: [] as string[],
    },

    // ── BLACKLIST (2) ────────────────────────────────────────────────────────
    {
      nome: "Sandro Ferreira", telefone: "912048048", email: "sandro.f@gmail.com",
      estado: "blacklist", totalSessoes: 1, totalGasto: 0, ultimaSessao: d(-150),
      dataNascimento: null, comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Comportamento inapropriado durante a sessão. Não remarcar. Não contactar.",
      etiquetas: [] as string[],
    },
    {
      nome: "Ricardo Alves", telefone: "917049049", email: "r.alves@hotmail.com",
      estado: "blacklist", totalSessoes: 0, totalGasto: 0, ultimaSessao: null,
      dataNascimento: null, comoNosConheceu: "google", fonte: "google",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: false,
      historicoAromasPreferidos: null, historicoCondicoesAlergias: null,
      historicoEstadoEmocional: null, historicoZonasTensao: null, historicoUltimaPausa: null,
      notasPessoais: "Marcou e cancelou 4 vezes. Comportamento abusivo por mensagem. Bloquear.",
      etiquetas: [] as string[],
    },

    // ── ANIVERSARIANTE EM MAIO (1 extra) ─────────────────────────────────────
    {
      nome: "Vera Lourenço", telefone: "963050050", email: "vera.l@gmail.com",
      estado: "ativa_recente", totalSessoes: 5, totalGasto: 240, ultimaSessao: d(-22),
      dataNascimento: new Date("1987-05-25"), comoNosConheceu: "instagram", fonte: "instagram",
      canalPreferido: "whatsapp", temWhatsapp: true, aceitaMarketing: true,
      historicoAromasPreferidos: "Rosa e pétalas — celebratórios.",
      historicoCondicoesAlergias: "Sem condições. Celebrar o aniversário com sessão especial.",
      historicoEstadoEmocional: "Muito alegre e extrovertida.",
      historicoZonasTensao: "Ombros e costas (trabalho de escritório).",
      historicoUltimaPausa: "Começou há 5 meses, frequência irregular.",
      notasPessoais: "Aniversário a 25 de maio — ESTA SEMANA! Enviar mensagem de parabéns e oferta especial.",
      etiquetas: [etNome("Aniversário este mês")].filter(Boolean) as string[],
    },
  ];

  // Inserir todos os clientes
  let criados = 0;
  for (const { etiquetas, ...data } of clientesData) {
    const cliente = await prisma.cliente.create({ data: data as Parameters<typeof prisma.cliente.create>[0]["data"] });
    if (etiquetas.length > 0) {
      await prisma.clienteEtiqueta.createMany({
        data: etiquetas.map(etiquetaId => ({ clienteId: cliente.id, etiquetaId })),
      });
    }
    criados++;
  }

  console.log(`✅ ${criados} clientes criados`);

  // Verificar totais por estado
  const porEstado = await prisma.cliente.groupBy({ by: ["estado"], _count: { id: true }, orderBy: { estado: "asc" } });
  console.log("\n📊 Distribuição por estado:");
  porEstado.forEach(r => console.log(`  ${r.estado.padEnd(18)} ${r._count.id}`));

  const total = await prisma.cliente.count();
  console.log(`\n🎯 Total de clientes na BD: ${total}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
